package sync

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// Transport defines how chunks are read and written during sync.
// This is the abstraction that allows the same Syncer to work with
// both local filesystem (.ohara/ directory) and remote cloud server.
type Transport interface {
	// ReadManifest returns the manifest (chunk index).
	// Returns an empty manifest if none exists yet.
	ReadManifest() (*Manifest, error)

	// WriteManifest persists the manifest.
	WriteManifest(m *Manifest) error

	// WriteChunk writes a compressed chunk to the transport.
	// chunkID is the content-addressed ID (8 hex chars).
	// data is the raw JSON bytes (FileTransport gzips them; remote sends as-is).
	// entry contains metadata about the chunk.
	WriteChunk(chunkID string, data []byte, entry ChunkEntry) error

	// ReadChunk reads a compressed chunk from the transport.
	// Returns the raw bytes (gzipped for FileTransport, JSON for remote).
	ReadChunk(chunkID string) ([]byte, error)

	// EnsureGitattributes creates or updates the .gitattributes file in the sync
	// directory with union-merge guidance for manifest files and binary markers for
	// compressed chunks. This makes the mirror git-friendly for team collaboration.
	EnsureGitattributes() error
}

// ─── FileTransport ──────────────────────────────────────────────────────────

// FileTransport reads/writes chunks to the local filesystem.
// This encapsulates all filesystem operations that were previously
// inline in the Syncer methods.
type FileTransport struct {
	syncDir string // Path to sync directory (e.g. .ohara/)
}

// NewFileTransport creates a FileTransport rooted at the given sync directory.
func NewFileTransport(syncDir string) *FileTransport {
	return &FileTransport{syncDir: syncDir}
}

// ReadManifest reads the manifest.json from the sync directory.
// Returns an empty manifest (Version=1) if the file does not exist.
func (ft *FileTransport) ReadManifest() (*Manifest, error) {
	path := filepath.Join(ft.syncDir, "manifest.json")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &Manifest{Version: 1}, nil
		}
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}
	return &m, nil
}

// WriteManifest writes the manifest to manifest.json in the sync directory.
func (ft *FileTransport) WriteManifest(m *Manifest) error {
	path := filepath.Join(ft.syncDir, "manifest.json")
	data, err := jsonMarshalManifest(m, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal manifest: %w", err)
	}
	return os.WriteFile(path, data, 0644)
}

// WriteChunk writes gzipped chunk data to the chunks/ subdirectory.
func (ft *FileTransport) WriteChunk(chunkID string, data []byte, _ ChunkEntry) error {
	chunksDir := filepath.Join(ft.syncDir, "chunks")
	if err := os.MkdirAll(chunksDir, 0755); err != nil {
		return fmt.Errorf("create chunks dir: %w", err)
	}

	chunkPath := filepath.Join(chunksDir, chunkID+".jsonl.gz")
	return writeGzip(chunkPath, data)
}

// ReadChunk reads gzipped chunk data from the chunks/ subdirectory.
func (ft *FileTransport) ReadChunk(chunkID string) ([]byte, error) {
	chunksDir := filepath.Join(ft.syncDir, "chunks")
	chunkPath := filepath.Join(chunksDir, chunkID+".jsonl.gz")
	return readGzip(chunkPath)
}

// GitattributesContent returns the desired .gitattributes file content.
// Exported so sync tests can verify idempotence without duplicating the literal string.
func GitattributesContent() []byte {
	return []byte(
		"# Auto-generated by ohara sync — do not edit manually\n" +
			"# Union merge for append-only manifest and chunk files (safe for concurrent syncs)\n" +
			"manifest.json merge=union\n" +
			"chunks/*.jsonl merge=union\n" +
			"*.jsonl merge=union\n" +
			"# Binary for compressed chunks (content-addressed, never need diffing)\n" +
			"*.jsonl.gz binary\n" +
			"chunks/*.jsonl.gz binary\n",
	)
}

// EnsureGitattributes creates or updates the .gitattributes file in the sync directory.
// Idempotent: safe to call on every export.
func (ft *FileTransport) EnsureGitattributes() error {
	path := filepath.Join(ft.syncDir, ".gitattributes")
	want := GitattributesContent()

	// Check if existing content matches what we'd write.
	if data, err := os.ReadFile(path); err == nil {
		if string(data) == string(want) {
			return nil // already correct
		}
	}
	return os.WriteFile(path, want, 0644)
}
